import type { CMSData } from "./types";
import { createEmptyCMSData } from "./defaults";

const now = new Date().toISOString();

export const legacySeedData: CMSData = {
  ...createEmptyCMSData(),
  projects: [
    {
      id: "1",
      title: "Brandify",
      subtitle: "Agencia de Marketing Digital",
      category: "Agency Website",
      services: "Design de Interface, Desenvolvimento Web",
      client: "Digital Innovations Agency",
      year: "2023",
      image: "",
      galleryImages: [],
      galleryPositions: [],
      link: "#",
      slug: "brandify",
      description:
        "Brandify e uma plataforma de marketing digital que ajuda empresas a criar e gerenciar suas marcas de forma eficiente e estrategica.",
      contentBlocks: [
        { type: "heading1", text: "Sobre Brandify" },
        {
          type: "paragraph",
          text: "Brandify e uma plataforma de marketing digital que ajuda empresas a criar e gerenciar suas marcas de forma eficiente e estrategica.",
        },
        { type: "heading2", text: "Funcionalidades" },
        {
          type: "unordered-list",
          items: [
            { text: "Design de Interface", children: [] },
            { text: "Desenvolvimento Web", children: [] },
            { text: "Gerenciamento de Conteudo", children: [] },
          ],
        },
      ],
      imageBgColor: "",
      imagePosition: "50% 50%",
      password: "",
      status: "published",
      tags: ["web", "marketing"],
      featured: true,
      seoTitle: "",
      seoDescription: "",
      createdAt: now,
      updatedAt: now,
      publishedAt: now,
    },
    {
      id: "2",
      title: "Shiro",
      subtitle: "Portfolio Pessoal",
      category: "Personal Portfolio",
      services: "Design de Interface, Desenvolvimento Web",
      client: "Gabriel Baltar",
      year: "2022",
      image: "",
      galleryImages: [],
      galleryPositions: [],
      link: "#",
      slug: "shiro",
      description: "Shiro e o portfolio pessoal de Gabriel Baltar, onde ele apresenta seus projetos e habilidades em design e desenvolvimento web.",
      contentBlocks: [
        { type: "heading1", text: "Sobre Shiro" },
        { type: "paragraph", text: "Shiro e o portfolio pessoal de Gabriel Baltar." },
      ],
      imageBgColor: "",
      imagePosition: "50% 50%",
      password: "",
      status: "published",
      tags: ["portfolio", "design"],
      featured: false,
      seoTitle: "",
      seoDescription: "",
      createdAt: now,
      updatedAt: now,
      publishedAt: now,
    },
    {
      id: "3",
      title: "Vivid",
      subtitle: "Apresentacao de Aplicativos",
      category: "App Showcase",
      services: "Design de Interface, Desenvolvimento Web",
      client: "Digital Innovations Agency",
      year: "2021",
      image: "",
      galleryImages: [],
      galleryPositions: [],
      link: "#",
      slug: "vivid",
      description: "Vivid e uma plataforma que apresenta e destaca aplicativos de alta qualidade.",
      contentBlocks: [
        { type: "heading1", text: "Sobre Vivid" },
        { type: "paragraph", text: "Vivid e uma plataforma que apresenta e destaca aplicativos de alta qualidade." },
      ],
      imageBgColor: "",
      imagePosition: "50% 50%",
      password: "",
      status: "published",
      tags: ["app", "showcase"],
      featured: false,
      seoTitle: "",
      seoDescription: "",
      createdAt: now,
      updatedAt: now,
      publishedAt: now,
    },
    {
      id: "4",
      title: "Capture",
      subtitle: "Agencia de Videos",
      category: "Video Agency",
      services: "Design de Interface, Desenvolvimento Web",
      client: "Digital Innovations Agency",
      year: "2020",
      image: "",
      galleryImages: [],
      galleryPositions: [],
      link: "#",
      slug: "capture",
      description: "Capture e uma agencia de videos que produz conteudo visual de alta qualidade.",
      contentBlocks: [],
      imageBgColor: "",
      imagePosition: "50% 50%",
      password: "",
      status: "draft",
      tags: ["video", "agency"],
      featured: false,
      seoTitle: "",
      seoDescription: "",
      createdAt: now,
      updatedAt: now,
      publishedAt: null,
    },
    {
      id: "5",
      title: "Automize",
      subtitle: "Agencia de Inteligencia Artificial",
      category: "AI Agency",
      services: "Design de Interface, Desenvolvimento Web",
      client: "Digital Innovations Agency",
      year: "2019",
      image: "",
      galleryImages: [],
      galleryPositions: [],
      link: "#",
      slug: "automize",
      description: "Automize e uma agencia de inteligencia artificial.",
      contentBlocks: [],
      imageBgColor: "",
      imagePosition: "50% 50%",
      password: "",
      status: "published",
      tags: ["ai", "agency"],
      featured: false,
      seoTitle: "",
      seoDescription: "",
      createdAt: now,
      updatedAt: now,
      publishedAt: now,
    },
    {
      id: "6",
      title: "Lyne",
      subtitle: "Portfolio e Agencia",
      category: "Portfolio & Agency",
      services: "Design de Interface, Desenvolvimento Web",
      client: "Digital Innovations Agency",
      year: "2018",
      image: "",
      galleryImages: [],
      galleryPositions: [],
      link: "#",
      slug: "lyne",
      description: "Lyne e um portfolio e agencia que apresenta projetos de design e desenvolvimento web de alta qualidade.",
      contentBlocks: [],
      imageBgColor: "",
      imagePosition: "50% 50%",
      password: "",
      status: "archived",
      tags: ["portfolio", "agency"],
      featured: false,
      seoTitle: "",
      seoDescription: "",
      createdAt: now,
      updatedAt: now,
      publishedAt: null,
    },
  ],
  experiences: [
    {
      id: "1",
      location: "San Francisco, CA",
      company: "Digital Innovations Agency",
      period: "Jan 2019 - Presente",
      role: "Senior Web Designer",
      tasks: [
        "Liderou o redesign de websites de alto trafego, resultando em 30% de aumento no engajamento.",
        "Gerenciou uma equipe de designers juniores.",
        "Colaborou com equipes multifuncionais.",
        "Implementou principios de design responsivo.",
      ],
      sortOrder: 1,
    },
    {
      id: "2",
      location: "Los Angeles, CA",
      company: "Creative Solutions Studio",
      period: "Jun 2013 - Dez 2018",
      role: "Web Designer",
      tasks: [
        "Projetou e desenvolveu mais de 50 websites customizados.",
        "Conduziu testes de usabilidade e pesquisa de usuario.",
        "Criou wireframes, mockups e prototipos.",
        "Utilizou HTML, CSS e JavaScript.",
      ],
      sortOrder: 2,
    },
    {
      id: "3",
      location: "Austin, TX",
      company: "TechWave LLC",
      period: "Abr 2008 - Mai 2013",
      role: "Front-End Developer / Designer",
      tasks: [
        "Desenvolveu e manteve o front-end de websites de e-commerce.",
        "Trabalhou com desenvolvedores back-end para integrar APIs.",
        "Garantiu padroes de acessibilidade.",
        "Criou assets visuais para campanhas.",
      ],
      sortOrder: 3,
    },
    {
      id: "4",
      location: "Seattle, WA",
      company: "Bright Ideas Web Solutions",
      period: "Jan 2006 - Mar 2008",
      role: "Junior Web Designer",
      tasks: [
        "Auxiliou no design e desenvolvimento de websites.",
        "Manteve e atualizou websites existentes.",
        "Participou de reunioes com clientes.",
        "Desenvolveu habilidades basicas de HTML e CSS.",
      ],
      sortOrder: 4,
    },
  ],
  education: [
    {
      id: "1",
      location: "Berkeley, CA",
      period: "2010 - 2012",
      degree: "Master of Science in Web Design and Development",
      university: "University of California",
      description: "Focado em tecnologias web avancadas, design de experiencia do usuario e desenvolvimento front-end.",
      sortOrder: 1,
    },
    {
      id: "2",
      location: "Seattle, WA",
      period: "2002 - 2006",
      degree: "Bachelor of Fine Arts in Graphic Design",
      university: "University of Washington",
      description: "Enfase em comunicacao visual, principios de design e midia digital.",
      sortOrder: 2,
    },
  ],
  certifications: [
    { id: "1", title: "Certified Web Developer (CWD)", issuer: "International Web Association, 2021", link: "https://www.coursera.org/", sortOrder: 1 },
    { id: "2", title: "User Experience (UX) Design Certification", issuer: "Nielsen Norman Group, 2018", link: "https://www.coursera.org/", sortOrder: 2 },
    { id: "3", title: "Advanced HTML5 and CSS3 Specialist", issuer: "W3Schools, 2016", link: "https://www.coursera.org/", sortOrder: 3 },
    { id: "4", title: "Google Analytics Individual Qualification (GAIQ)", issuer: "Google, 2015", link: "https://www.coursera.org/", sortOrder: 4 },
  ],
  stack: [
    { id: "1", name: "Figma", description: "Design de interfaces", color: "#0055FF", link: "https://www.figma.com/", sortOrder: 1 },
    { id: "2", name: "Framer", description: "No-code web design", color: "#0055FF", link: "https://www.framer.com/", sortOrder: 2 },
    { id: "3", name: "Notion", description: "Gerenciamento de projetos", color: "#17CF97", link: "https://notion.so/", sortOrder: 3 },
    { id: "4", name: "Stripe", description: "Plataforma de pagamentos", color: "#5417D7", link: "https://stripe.com/", sortOrder: 4 },
    { id: "5", name: "Zoom", description: "Colaboracao", color: "#007DFC", link: "https://zoom.us/", sortOrder: 5 },
    { id: "6", name: "Cal.com", description: "Comunicacao", color: "#CA9352", link: "https://cal.com/", sortOrder: 6 },
  ],
  awards: [
    { id: "1", title: "Site of the day", issuer: "Awwwards, 2023", link: "https://www.awwwards.com/", sortOrder: 1 },
    { id: "2", title: "Site of the month", issuer: "Awwwards, 2020", link: "https://www.awwwards.com/", sortOrder: 2 },
    { id: "3", title: "Website of the day", issuer: "CSS Design Awards, 2018", link: "https://www.cssdesignawards.com/", sortOrder: 3 },
    { id: "4", title: "Site of the day", issuer: "FWA, 2016", link: "https://thefwa.com/", sortOrder: 4 },
  ],
  recommendations: [
    {
      id: "1",
      name: "Jane Smith",
      role: "Chief Marketing Officer at Digital Innovations Agency",
      quote: "\"A expertise de design do Gabriel e sua abordagem inovadora foram fundamentais para o sucesso da nossa agencia.\"",
      sortOrder: 1,
    },
    {
      id: "2",
      name: "Michael Brown",
      role: "Founder of Creative Solutions Studio",
      quote: "\"Gabriel e um designer excepcional com um olhar aguado para detalhes e uma compreensao profunda de experiencia do usuario.\"",
      sortOrder: 2,
    },
    {
      id: "3",
      name: "Lisa Turner",
      role: "Senior Developer at TechWave LLC",
      quote: "\"Trabalhar com Gabriel foi um prazer. Seu espirito colaborativo e habilidades tecnicas fizeram nossos projetos fluirem de forma suave.\"",
      sortOrder: 3,
    },
  ],
  blogPosts: [
    {
      id: "1",
      title: "The Future of Web Design: Trends to Watch in 2024",
      subtitle: "",
      publisher: "Web Design Journal",
      date: "15 de mai. de 2024",
      description: "Uma analise aprofundada das tendencias emergentes em web design.",
      image: "",
      imageBgColor: "",
      imagePosition: "50% 50%",
      galleryPositions: [],
      galleryImages: [],
      content: "",
      slug: "the-future-of-web-design-trends-to-watch-in-2024",
      contentBlocks: [
        { type: "heading1", text: "O Futuro do Design Web" },
        { type: "paragraph", text: "O design web esta em constante evolucao, e 2024 promete trazer mudancas significativas." },
        { type: "heading2", text: "Tendencias Principais" },
        {
          type: "unordered-list",
          items: [
            { text: "Design com IA", children: [] },
            { text: "Micro-interacoes", children: [] },
            { text: "Design Sustentavel", children: [] },
          ],
        },
      ],
      status: "published",
      tags: ["design", "trends"],
      featured: true,
      author: "Gabriel Baltar",
      readTime: "5 min",
      link: "",
      category: "",
      services: "",
      password: "",
      seoTitle: "",
      seoDescription: "",
      createdAt: now,
      updatedAt: now,
      publishedAt: now,
    },
    {
      id: "2",
      title: "Responsive Design Best Practices",
      subtitle: "",
      publisher: "Modern Web Magazine",
      date: "11 de mai. de 2024",
      description: "As melhores praticas para criar websites responsivos.",
      image: "",
      imageBgColor: "",
      imagePosition: "50% 50%",
      galleryPositions: [],
      galleryImages: [],
      content: "",
      slug: "responsive-design-best-practices",
      contentBlocks: [
        { type: "heading1", text: "Praticas de Design Responsivo" },
        { type: "paragraph", text: "O design responsivo nao e mais uma opcao, e uma necessidade." },
      ],
      status: "published",
      tags: ["responsive", "css"],
      featured: false,
      author: "Gabriel Baltar",
      readTime: "4 min",
      link: "",
      category: "",
      services: "",
      password: "",
      seoTitle: "",
      seoDescription: "",
      createdAt: now,
      updatedAt: now,
      publishedAt: now,
    },
    {
      id: "3",
      title: "The Art of Minimalist Web Design",
      subtitle: "",
      publisher: "Modern Web Magazine",
      date: "10 de mai. de 2024",
      description: "Os principios do design minimalista.",
      image: "",
      imageBgColor: "",
      imagePosition: "50% 50%",
      galleryPositions: [],
      galleryImages: [],
      content: "",
      slug: "the-art-of-minimalist-web-design",
      contentBlocks: [
        { type: "heading1", text: "A Arte do Design Minimalista" },
        { type: "paragraph", text: "Menos e mais - essa e a essencia do design minimalista." },
      ],
      status: "draft",
      tags: ["minimalism", "design"],
      featured: false,
      author: "Gabriel Baltar",
      readTime: "6 min",
      link: "",
      category: "",
      services: "",
      password: "",
      seoTitle: "",
      seoDescription: "",
      createdAt: now,
      updatedAt: now,
      publishedAt: null,
    },
  ],
  pages: [
    {
      id: "1",
      title: "Sobre",
      slug: "sobre",
      description: "Pagina institucional sobre o portfolio.",
      contentBlocks: [
        { type: "heading1", text: "Sobre mim" },
        { type: "paragraph", text: "Sou um designer apaixonado por criar experiencias digitais memoraveis." },
      ],
      status: "published",
      seoTitle: "",
      seoDescription: "",
      createdAt: now,
      updatedAt: now,
      publishedAt: now,
    },
  ],
  media: [],
};
